version: '3.8'

services:
  mysql:
    build:
      context: .
    image: mysql:3.8
    restart: unless-stopped
    container_name: gestione_magazzino
    volumes: 
      - data-volume:/var/lib/mysql
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=admin

volumes:
  data-volume:
